-- =============================================
-- TOKOPELUANG MONETIZATION
-- Investment Technology Indonesia
-- =============================================

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  transaction_code text not null unique,
  customer_name text not null,
  customer_email text,
  description text not null,
  gross_amount bigint not null check (gross_amount >= 0),
  platform_fee bigint not null default 0 check (platform_fee >= 0),
  partner_amount bigint not null default 0 check (partner_amount >= 0),
  payment_status text not null default 'pending'
    check (payment_status in ('pending', 'paid', 'failed', 'expired', 'refunded')),
  settlement_status text not null default 'unsettled'
    check (settlement_status in ('unsettled', 'processing', 'settled')),
  payment_reference text,
  paid_at timestamptz,
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.transactions enable row level security;

drop policy if exists "Admin can read transactions"
on public.transactions;

drop policy if exists "Admin can insert transactions"
on public.transactions;

drop policy if exists "Admin can update transactions"
on public.transactions;

drop policy if exists "Admin can delete transactions"
on public.transactions;

create policy "Admin can read transactions"
on public.transactions
for select
to authenticated
using (
  (auth.jwt() ->> 'email') = 'alma.budsteddy88@gmail.com'
);

create policy "Admin can insert transactions"
on public.transactions
for insert
to authenticated
with check (
  (auth.jwt() ->> 'email') = 'alma.budsteddy88@gmail.com'
);

create policy "Admin can update transactions"
on public.transactions
for update
to authenticated
using (
  (auth.jwt() ->> 'email') = 'alma.budsteddy88@gmail.com'
)
with check (
  (auth.jwt() ->> 'email') = 'alma.budsteddy88@gmail.com'
);

create policy "Admin can delete transactions"
on public.transactions
for delete
to authenticated
using (
  (auth.jwt() ->> 'email') = 'alma.budsteddy88@gmail.com'
);

create index if not exists transactions_payment_status_idx
on public.transactions(payment_status);

create index if not exists transactions_created_at_idx
on public.transactions(created_at desc);
